import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  Header from "./components/header"
import Footer from "./components/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "eLibrary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
       <body>
         <Header />
         <div className="w-full px-4 mx-auto">
             {children}
             <Footer />
         </div>
       </body>
     </html>
  );
}
